src/Entity/Event.php
<?php

namespace App\Entity;

use App\Repository\EventRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: EventRepository::class)]
class Event
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 100)]
    private ?string $name = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $slug = null;

    #[ORM\Column(length: 255)]
    private ?string $description = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $detail = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $quote = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $startDate = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $endTime = null;

    #[ORM\Column]
    private ?int $nb_rooms = null;

    #[ORM\Column(length: 30)]
    private ?string $type = null;

    #[ORM\Column(length: 30)]
    private ?string $status = null;

    #[ORM\Column(length: 20, nullable: true)]
    private ?string $access = null;

    /**
     * @var Collection<int, Photo>
     */
    #[ORM\OneToMany(targetEntity: Photo::class, mappedBy: 'event')]
    private Collection $photos;

    /**
     * @var Collection<int, EventCategory>
     */
    #[ORM\ManyToMany(targetEntity: EventCategory::class, mappedBy: 'events')]
    private Collection $eventCategories;

    /**
     * @var Collection<int, EventParticipation>
     */
    #[ORM\OneToMany(targetEntity: EventParticipation::class, mappedBy: 'event', orphanRemoval: true)]
    private Collection $eventParicipations;

    public function __construct()
    {
        $this->photos = new ArrayCollection();
        $this->eventCategories = new ArrayCollection();
        $this->eventParicipations = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(?string $slug): static
    {
        $this->slug = $slug;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getDetail(): ?string
    {
        return $this->detail;
    }

    public function setDetail(?string $detail): static
    {
        $this->detail = $detail;

        return $this;
    }

    public function getQuote(): ?string
    {
        return $this->quote;
    }

    public function setQuote(?string $quote): static
    {
        $this->quote = $quote;

        return $this;
    }

    public function getStartDate(): ?\DateTimeInterface
    {
        return $this->startDate;
    }

    public function setStartDate(\DateTimeInterface $startDate): static
    {
        $this->startDate = $startDate;

        return $this;
    }

     //It transforms the type of the StartDate'format 
    public function getFormattedStartDate(): ?string
    {
        return $this->startDate ? $this->startDate->format('d.m.Y') : null;
    }


    public function getEndTime(): ?\DateTimeInterface
    {
        return $this->endTime;
    }

    public function setEndTime(\DateTimeInterface $endTime): static
    {
        $this->endTime = $endTime;

        return $this;
    }

    //It transform the type of the EndTime'format 
    public function getFormattedEndTime(): ?string
    {
        return $this->endTime ? $this->endTime->format('d.m.Y') : null;
    }


    public function getNbRooms(): ?int
    {
        return $this->nb_rooms;
    }

    public function setNbRooms(int $nb_rooms): static
    {
        $this->nb_rooms = $nb_rooms;

        return $this;
    }

    public function getType(): ?string
    {
        return $this->type;
    }

    public function setType(string $type): static
    {
        $this->type = $type;

        return $this;
    }

    public function getStatus(): ?string
    {
        return $this->status;
    }

    public function setStatus(string $status): static
    {
        $this->status = $status;

        return $this;
    }

    public function getAccess(): ?string
    {
        return $this->access;
    }

    public function setAccess(?string $access): static
    {
        $this->access = $access;

        return $this;
    }

    /**
     * @return Collection<int, Photo>
     */
    public function getPhotos(): Collection
    {
        return $this->photos;
    }

    public function addPhoto(Photo $photo): static
    {
        if (!$this->photos->contains($photo)) {
            $this->photos->add($photo);
            $photo->setEvent($this);
        }

        return $this;
    }

    public function removePhoto(Photo $photo): static
    {
        if ($this->photos->removeElement($photo)) {
            // set the owning side to null (unless already changed)
            if ($photo->getEvent() === $this) {
                $photo->setEvent(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, EventCategory>
     */
    public function getEventCategories(): Collection
    {
        return $this->eventCategories;
    }

    public function addEventCategory(EventCategory $eventCategory): static
    {
        if (!$this->eventCategories->contains($eventCategory)) {
            $this->eventCategories->add($eventCategory);
            $eventCategory->addEvent($this);
        }

        return $this;
    }

    public function removeEventCategory(EventCategory $eventCategory): static
    {
        if ($this->eventCategories->removeElement($eventCategory)) {
            $eventCategory->removeEvent($this);
        }

        return $this;
    }

    /**
     * @return Collection<int, EventParticipation>
     */
    public function getEventParicipations(): Collection
    {
        return $this->eventParicipations;
    }

    public function addEventParicipation(EventParticipation $eventParicipation): static
    {
        if (!$this->eventParicipations->contains($eventParicipation)) {
            $this->eventParicipations->add($eventParicipation);
            $eventParicipation->setEvent($this);
        }

        return $this;
    }

    public function removeEventParicipation(EventParticipation $eventParicipation): static
    {
        if ($this->eventParicipations->removeElement($eventParicipation)) {
            // set the owning side to null (unless already changed)
            if ($eventParicipation->getEvent() === $this) {
                $eventParicipation->setEvent(null);
            }
        }

        return $this;
    }
}

src/Entity/Photo.php
<?php

namespace App\Entity;

use App\Repository\PhotoRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: PhotoRepository::class)]
class Photo
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 100, nullable: true)]
    private ?string $title = null;

    #[ORM\Column(length: 150, nullable: true)]
    private ?string $alt_description = null;

    #[ORM\Column(length: 255)]
    private ?string $path = null;

    #[ORM\Column(length: 30, nullable: true)]
    private ?string $type = null;

    #[ORM\Column(nullable: true)]
    private ?bool $is_selected = null;

    #[ORM\ManyToOne(inversedBy: 'photos')]
    private ?User $user = null;

    #[ORM\ManyToOne(inversedBy: 'photos')]
    private ?Event $event = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(?string $title): static
    {
        $this->title = $title;

        return $this;
    }

    public function getAltDescription(): ?string
    {
        return $this->alt_description;
    }

    public function setAltDescription(?string $alt_description): static
    {
        $this->alt_description = $alt_description;

        return $this;
    }

    public function getPath(): ?string
    {
        return $this->path;
    }

    public function setPath(string $path): static
    {
        $this->path = $path;

        return $this;
    }

    public function getType(): ?string
    {
        return $this->type;
    }

    public function setType(?string $type): static
    {
        $this->type = $type;

        return $this;
    }

    public function isSelected(): ?bool
    {
        return $this->is_selected;
    }

    public function setSelected(?bool $is_selected): static
    {
        $this->is_selected = $is_selected;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): static
    {
        $this->user = $user;

        return $this;
    }

    public function getEvent(): ?Event
    {
        return $this->event;
    }

    public function setEvent(?Event $event): static
    {
        $this->event = $event;

        return $this;
    }
}

templates/event/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Our Events{% endblock %}
{% block meta %}Join Photoclub for cultural exchanges .{% endblock %}

{% block body %}

<div class="banner"></div>
    <div class="content">
        <h1 class="banner-title">OUR EVENTS</h1>
        <div class="subtitle">
            <p class="banner-text">Be curious</p>
            {# <div class="underscore-blink"> </div> #}
        </div>
    </div>
</div>

<div class="breadcrumb breadcrumb-dark">
    <p><a href="{{ path('app_home') }}">Home </a> > All Events </p>
</div>

<section class="content" id="events-index">
    {% for event in ongoingEvents %}
        <div class="container-event">
            <div id="photo-event">
                {% for photo in event.photos %}
                <figure>
                    <a href="{{ path('show_event', { slug : event.slug  }) }}">
                    <img src="{{ asset('img/action/event/' ~ event.id ~ '/banner/' ~ photo.path) }}" alt="{{ photo.altDescription }}"></a>
                </figure>
                 {% endfor %}

            </div>
            <article id="infos-event">
                <h2 class="text-n1">{{event.name}}<span class=""> >></span></h2>
                <p id="resume-event"><span>Description : </span>{{event.description}}</p>
                <div id="details-event">
                    {# <p><span>Date : </span> {{event.startDate|format('d.m.Y')}} <span>|</span> {{event.endTime|format('d.m.Y')}}</p>  #}
                    <p><span>Statut : </span>
                        <span class="status {{ event.status == 'OPEN' ? 'open' : 
                        (event.status == 'CLOSED' ? 'closed' : 
                        (event.status == 'PENDING' ? 'pending' : 
                        (event.status == 'ARCHIVED' ? 'archived' : 'status-default'))) }}">
                        {{ event.status }}
                        </span>
                    </p>
                    <p><span>Access : </span> {{event.access}}</p>
                    {# <p><span>Capacity : </span> {{event.nbReversationMade}}  /  {{event.nbRooms}}</p> #}
                    <p><span>Capacity : </span> {{event.nbRooms}}</p>
                </div>
                <div id="btn-event">
                    <div class="button btn6"><a href="{{ path('show_event', { slug : event.slug  }) }}">LEARN MORE</a></div>
                </div>
            </article>
        </div>
    {% endfor %}

</section>
  
<div id="previous-link">
    <p class="past-event-btn"><i class="ri-eye-close-fill"></i></p>
    <div>
        <h3>To see all our previous events </h3>
        <a href="{{ path('app_archives')}}">check here <i class="ri-arrow-right-double-fill"></i> </a> 
    </div>
</div>

<script src= "{{ asset('js/pagesShow.js') }}"></script>

<script></script>
{% endblock %}

templates/event/newParticipation.html.twig
{% extends 'base.html.twig' %}

{% block title %}Event reservation{% endblock %}
{% block meta %}Join our upcoming art event with just a few clicks.{% endblock %}

{% block body %}

<div class="banner">
    <div class="content">
        <h1 class="banner-title">{{event.name}}</h1>
        <div class="subtitle">
            <p class="banner-text">Be curious</p>
            {# <div class="underscore-blink"> </div> #}
        </div>
    </div>
</div>

{# <style>
    body {background-color: #151515;}
</style> #}

<div class="breadcrumb breadcrumb-light">
    <p><a href="{{ path('app_home') }}">Home </a> >  <a href="{{ path('app_event') }}">All Events</a> > <a href="{{ path('show_event', { slug : event.slug  }) }}">{{event.name}}</a> > Reservation</p>
</div>

<section class="content register-user" id="participation-page">
    <div id="register-container">
        <div id="separator"></div>

        <div class="left-register" id="l-participation">
            <img src="{{ asset('img/general/silhouette.webp') }}" alt="Silhouette of the photographer.">
        </div>

        <div class="right-register" id="r-participation">
            <div id="title-register">
                <h2>Make a reservation<span class="underscore">_</span></h2>
                <p><span id="name">{{event.name}}</span><span id="pipe-separator">|</span> {{event.startDate|format('d.m.Y')}} - {{event.endTime|format('d.m.Y')}}</p>
            </div>

            {% if app.user %}
            <div id="form-register">

                {{ form_start(formSendParticipation)}}
                    {{ form_errors(formSendParticipation)}}
                    {{ form_row(formSendParticipation.firstname)}}
                    {{ form_row(formSendParticipation.lastname)}}
                        {{ form_row(formSendParticipation.submit, { 'attr' : { 'class': 'btn btn6' } })}}
                {{ form_end(formSendParticipation)}}
            </div>

            {% else %}
            <div id="form-register">
                {{ form_start(formSendParticipationPublic)}}
                    {{ form_errors(formSendParticipationPublic)}}
                    {{ form_row(formSendParticipationPublic.firstname)}}
                    {{ form_row(formSendParticipationPublic.lastname)}}
                    {{ form_row(formSendParticipationPublic.email)}}
                        {{ form_row(formSendParticipationPublic.submit, { 'attr' : { 'class': 'btn btn6' } })}}
                {{ form_end(formSendParticipationPublic)}}
            </div>
            {% endif %}
        </div>

    </div>
</section>

{% endblock %}

templates/event/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{event.name}} - PHOTOCLUB {% endblock %}
{% block meta %}Enter into PHOTOCLUB's upcoming art event details, theme, and highlights. Join fellow art enthusiasts to share, discover, and connect. Learn more about {{event.name}}!{% endblock %}

{% block body %}


<div class="banner">
    <div class="content">
        <h1 class="banner-title">{{event.name}}</h1>
        <div class="subtitle">
            <p class="banner-text">We take care of our cultural distractions</p>
            {# <div class="underscore-blink"> </div> #}
        </div>
    </div>
</div>

<div class="breadcrumb breadcrumb-dark">
    <p><a href="{{ path('app_home') }}">Home </a> >  <a href="{{ path('app_event') }}">All Events</a> > {{event.name}} </p>
</div>

<section class="" id="event-show">
    <div id="header">
        {% for photo in event.photos %}
        <figure>
            <img src="{{ asset('img/action/event/' ~ event.id ~ '/banner/' ~ photo.path) }}" alt="{{ photo.altDescription }}"></a>
        </figure>
         {% endfor %}

        {# <div id="quote">
            <span class="quote-style"> &lt; </span>
            <p id="quote-text">{{event.quote}}</p>
            <span class="quote-style">></span>
        </div> #}
    </div>

    <div id="details-event">
        <div id="about-event">
            <h3 class="text-n1">About the <span id="subtitle">{{event.name}}</span></h3>
            <p><span>Description : </span>{{event.detail}}</p>
        </div>
    

        <div id="info">
            {# <p class="text-n2">Details >></p> #}
            <div id="list-infos">
                <div id="list-info">

                    {# <div>
                        <span>Date : </span>   <p>{{event.startDate|format('d.m.Y')}} <span> - </span> {{event.endTime|format('d.m.Y')}}</p> #}
                    {# </div>  #}

                    {# <div>
                        <span style="visibility:hidden;">Date : </span>  <span></span> <p>{{event.endDate|formatDate}} <span> - </span> {{event.endTime|date('H:i')}}</p>
                    </div> #}

                    <div><span>Capacity :</span>  <p> {{ event.nbRooms}}  </p> </div>

                    <div><span>Status :</span> <span></span> 
                            <div>
                                    <span class="status {{ event.status == 'OPEN' ? 'open' : 
                                    (event.status == 'CLOSED' ? 'closed' : 
                                    (event.status == 'PENDING' ? 'pending' : 
                                    (event.status == 'ARCHIVED' ? 'archived' : 'status-default'))) }}">
                                    {{ event.status }}
                                    </span>
                            </div> 
                    </div>

                    <div><span>Access :</span>  <p>{{event.access}}  </p> </div>
                    
                    
                </div>
            </div>
        </div>


        {% if app.user %}
            {% if existingParticipation %}
                    <div id="expo-participate">
                            <div id="btn-event">
                                <div class="button btn-off">PARTICIPATE</div>
                            </div>
                            <p>You are already subscribed to this event.</p>
                    </div>
            {% endif %}
        {% endif %}

            {# {% if event.nbReversationRemaining == 0 and event.status == 'CLOSED' %}
                <div id="expo-participate">
                        <div id="btn-event">
                                <div class="button btn-off">PARTICIPATE</div>
                        </div>
                        <p>No more place available for this event.</p>
                </div>
            {% elseif event.status == 'CLOSED' %} #}
            {% if event.status == 'CLOSED' %} 
            <div id="expo-participate">
                <div id="expo-participate">
                    <div id="btn-event">
                            <div class="button btn-off">CLOSED</div>
                    </div>
                    <p>This event is closed.</p>
                </div>
            </div>
            {% elseif event.status == 'OPEN' %}
                {% if event.access == 'private' and not app.user %}
                    {# user is not login and the event is private #}
                    <div id="expo-participate">
                        <div id="btn-event">
                            <div class="button btn-off">PARTICIPATE</div>
                        </div>
                        <p>You must be logged in to participate : <span><a href="{{ path('app_login')}}">Login</a>.</span> <br>
                        Don't have an account yet? <span><a href="{{path('app_register')}}">Create one now!</a></span> </p>
                    </div>
                {% else %}
                    <div id="expo-participate">
                        <div id="btn-event">
                            {# <a href="{{ path('event_new_participation', {'id': event.id }) }}"><div id="btn-participate-expo" class="button btn6">PARTICIPATE</div></a> #}
                            <a href="{{ path('app_contact', {'id': event.id })}}">PARTICIPATE</a>
                        </div>
                    </div>
                {% endif %}
            {% endif %}
       

    </div>

</section>
        {% if event.status == 'ARCHIVED' %}
            <p>Photos</p>
        {% endif %}



    {# {% if event.status != 'ARCHIVED' %}
        {% if event.status == 'PENDING' %}
            <p>Registration will open soon</p>
        {% else %}
            <p>Do you want to participate ?<br>
            {% if existingParticipation %}
                <p>You are already participating</p>
            {% elseif event.nbReversationRemaining == 0 and event.status == 'CLOSED' %}
                <p>No more space available for this exhibition</p>
            {% elseif event.status == 'OPEN' %}
                <a href="{{ path('event_new_participation', {'id': event.id }) }}">Click here!</a></p>
            {% endif %}
            
            </p>
        {% endif %}
    {% endif %} #}


    <script src= "{{ asset('js/pagesShow.js') }}"></script>
    <script src= "{{ asset('js/gsap.min.js') }}"></script>
 

{% endblock %}